name: Launch automated testing
   # Triger that will launch this action
on:
  pull_request:
    types: [opened, reopened] #When a pull request is opened or reopened will trigger this action


#The action that will be performed once the action is triggered
jobs:
   run_tests:   
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up JDK 21
          uses: actions/setup-java@v1
          with:
            java-version: '21'
        - name: Build
          run: mvn -f /ironlibrary clean compile
        - name: Test
          run: mvn clean test
